/* Pact / the private game room. One store, semantic views, native navigation. */
(function(){
'use strict';
const M=window.PactModel,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const KEY='pactRoomStateV2',escapeHtml=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const e=escapeHtml,asset=p=>M.ASSETS[typeof p==='string'?p:p.type]||'habit';
const names={EA:'Eeshita',NA:'Naina',MR:'Mira',JV:'Jay',RS:'Riya',KN:'Kabir',PR:'Priya',MS:'Meera',AR:'Aarav',NK:'Nikita',AS:'Arjun',LS:'Leah',VK:'Vivaan'};
const symbols={proof:'✓',race:'↗',invite:'◇',check:'✓',create:'P',result:'✧',jar:'◉',number:'№',profile:'◎'};
const hints={Habit:'A day tile for every time you show up.',Prediction:'Pick a side. Results stay sealed until the reveal.',Race:'A little movement. A little friendly competition.',Number:'Keep your guess face down until the actual result.',Jar:'One coin for each recorded slip-up.',Elimination:'Everyone starts in. Who will still be standing?'};
const objectLabels={habit:'THE HABIT',prediction:'THE PREDICTION',race:'THE RACE',number:'THE GUESS',jar:'THE JAR',elimination:'THE LAST ONE STANDING',proof:'THE PROOF',member:'THE MEMBERSHIP'};
let state,filter='All',statusFilter='active',search='',selectedType=false,currentRoute='',draft=null,toastTimer,photoDraft=null,dragStat=null;
try{const saved=localStorage.getItem(KEY);state=saved?M.normalize(JSON.parse(saved)):M.migrate(JSON.parse(localStorage.getItem('pactPrototypeState')||'null'));}catch{state=M.initial();}
let scrollPositions={};try{scrollPositions=JSON.parse(sessionStorage.getItem('pactRoomScroll')||'{}');}catch{}
function decodeId(value){try{return decodeURIComponent(value);}catch{return '';}}
function find(id){return state.pacts.find(p=>p.id===id);}
function personName(id){return id==='EA'?state.profile.name.split(' ')[0]:(state.peopleNames?.[id]||names[id]||id);}
function initials(name){return name.trim().split(/\s+/).slice(0,2).map(s=>s[0]).join('').toUpperCase();}
function avatars(people){return `<div class="avatars">${people.slice(0,3).map(id=>`<span aria-label="${e(personName(id))}">${e(id==='EA'?initials(state.profile.name):id)}</span>`).join('')}${people.length>3?`<span>+${people.length-3}</span>`:''}</div>`;}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3500);}
function activity(kind,title,text,pactId,extra={}){state.activity.unshift({id:M.uid(),kind,title,text,pactId,createdAt:new Date().toISOString(),...extra});state.activity=state.activity.slice(0,100);}
function transaction(change,message,animation){
  const before=structuredClone(state);let changed;
  try{changed=change();if(changed===false){state=before;return false;}localStorage.setItem(KEY,JSON.stringify(state));}catch{state=before;toast('Could not save this change. Free some device space and try again.');return false;}
  renderAll();if(message)toast(message);if(animation)window.PactScene?.play(animation);return true;
}
function safeImage(url){return typeof url==='string'&&/^data:image\/(png|jpeg|webp);base64,/.test(url)?url:'';}
function formatDate(value){const d=new Date(value+'T12:00:00');return Number.isNaN(d.getTime())?'Date to come':d.toLocaleDateString('en',{month:'short',day:'numeric'});}
function endDate(p){return M.dateOffset(p.totalDays-1,new Date(p.startDate+'T12:00:00'));}
function summary(p){
  if(p.status==='completed')return 'A promise kept. A story to tell.';
  if(p.status==='pending')return 'An invitation to put your word on it.';
  if(p.type==='Habit')return `${M.completedDays(p).size} of ${p.totalDays} days kept${Object.values(p.proofs).some(v=>v.status==='pending')?' · Proof waiting':''}`;
  if(p.type==='Prediction')return `${Object.keys(p.votes).length} of ${p.people.length} predictions sealed`;
  if(p.type==='Number')return `${Object.keys(p.guesses).length} ${Object.keys(p.guesses).length===1?'guess':'guesses'} face down`;
  if(p.type==='Race'){const lead=Object.entries(p.scores).sort((a,b)=>b[1]-a[1])[0];return lead?`${personName(lead[0])} leads with ${lead[1]} runs`:'The starting line is yours.';}
  if(p.type==='Jar')return `${p.violations} little slips, duly recorded`;
  return `${p.people.length-p.retired.length} of ${p.people.length} still standing`;
}
function card(p,i=0){return `<article class="pact-card" data-pact="${e(p.id)}" data-object="${asset(p)}"><div class="object-portrait"><span class="object-number">NO. ${String(M.TYPES.indexOf(p.type)+1).padStart(2,'0')}</span><span class="card-type">${e(p.type)}</span><img src="assets/objects/${asset(p)}.png" width="960" height="720" loading="lazy" alt="${e(p.type)} object"></div><div class="card-copy"><p class="eyebrow">${e(p.room)}</p><h3>${e(p.title)}</h3><p>${e(summary(p))}</p></div><div class="card-bottom">${avatars(p.people)}<span class="stake-label"><span class="stake-dot" aria-hidden="true">◇</span>${e(p.stake)}</span></div><a class="card-open" href="#challenge/${encodeURIComponent(p.id)}" aria-label="Open ${e(p.title)}"></a></article>`;}
function renderHome(){
  const visible=state.pacts.filter(p=>filter==='All'||p.context===filter);
  $('#pactGallery').innerHTML=visible.map(card).join('')||empty('A little room for something new.','Make a promise just for this company.');
  const proof=state.activity.find(a=>a.kind==='proof'&&a.pending),focus=state.pacts.find(p=>p.type==='Habit'&&p.status==='active');
  const invitation=state.pacts.find(p=>p.status==='pending');
  const cards=[];
  if(proof&&state.settings.reminders)cards.push(`<article class="attention-card"><span class="attention-symbol" aria-hidden="true">P</span><div class="attention-copy"><h3>${e(proof.title)}</h3><p>${e(proof.text)}</p></div><button class="text-button" data-review="${e(proof.id)}">Review proof ↗</button></article>`);
  else if(focus)cards.push(`<article class="attention-card"><span class="attention-symbol" aria-hidden="true">✓</span><div class="attention-copy"><h3>A little closer to who you want to be.</h3><p>${e(focus.title)} · ${e(summary(focus))}</p></div><a class="text-button" href="#challenge/${e(focus.id)}">Check in ↗</a></article>`);
  else cards.push(`<article class="attention-card"><span class="attention-symbol">P</span><div class="attention-copy"><h3>A clean slate. A good beginning.</h3><p>There's room for your next promise.</p></div><a class="text-button" href="#create">Make a pact ↗</a></article>`);
  if(invitation)cards.push(`<article class="attention-card"><span class="attention-symbol" aria-hidden="true">◇</span><div class="attention-copy"><h3>A coffee says you can call it.</h3><p>${e(invitation.title)}</p></div><a class="text-button" href="#challenge/${e(invitation.id)}">Take a look ↗</a></article>`);
  else cards.push(`<article class="attention-card"><span class="attention-symbol" aria-hidden="true">↗</span><div class="attention-copy"><h3>Better together, every time.</h3><p>Your people. Your next small challenge.</p></div><a class="text-button" href="#create">Start something ↗</a></article>`);
  $('#attentionGrid').innerHTML=cards.join('');
}
function empty(title,text){return `<div class="empty-state"><h3>${e(title)}</h3><p>${e(text)}</p><a class="button" href="#create">Make a pact ↗</a></div>`;}
function renderSpaces(){
  $('#pactTabs').innerHTML=[['active','On the table'],['pending','Invitations'],['completed','The keepsakes']].map(([id,label])=>`<button type="button" data-status="${id}" class="${id===statusFilter?'active':''}" aria-pressed="${id===statusFilter}">${label} <span>${state.pacts.filter(p=>p.status===id).length}</span></button>`).join('');
  const pacts=state.pacts.filter(p=>p.status===statusFilter&&`${p.title} ${p.room} ${p.stake} ${p.type} ${p.people.map(personName).join(' ')}`.toLowerCase().includes(search.toLowerCase()));
  $('#spaceGrid').innerHTML=`<p class="collection-status" role="status">${pacts.length} ${pacts.length===1?'pact':'pacts'} ${statusFilter==='completed'?'to remember':'in this collection'}</p><div class="pact-gallery">${pacts.map(card).join('')||empty(search?'No pact by that name.':'Nothing here. Yet.',search?'Try another title, person, or stake.':'Every good story starts with a small promise.')}</div>`;
}
function renderActivity(){
  $('#activityList').innerHTML=state.activity.map(a=>`<article class="activity-row"><span class="activity-icon" aria-hidden="true">${symbols[a.kind]||'◇'}</span><div><h2>${e(a.title)}</h2><p>${e(a.text)}</p>${a.createdAt?`<time datetime="${e(a.createdAt)}">${new Date(a.createdAt).toLocaleString('en',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</time>`:''}</div>${a.pending?`<button class="text-button" data-review="${e(a.id)}">Review proof ↗</button>`:find(a.pactId)?`<a class="text-button" href="#challenge/${e(a.pactId)}">View pact ↗</a>`:''}</article>`).join('')||empty('A quiet room.','Your shared moments will appear here.');
  $('.notification-dot').hidden=!state.activity.some(a=>a.pending);
}
function stats(){const completed=state.pacts.filter(p=>p.completedAt),wins=completed.filter(p=>p.winners?.includes('EA')).length,losses=completed.filter(p=>p.winners?.length&&!p.winners.includes('EA')).length;return {lost:{label:'Pacts lost',value:state.baseline.lost+losses},won:{label:'Pacts won',value:state.baseline.won+wins},streak:{label:'Best streak',value:Math.max(state.baseline.streak,...state.pacts.filter(p=>p.type==='Habit').map(p=>M.completedDays(p).size))+'d'},accuracy:{label:'Called it',value:Math.round((state.baseline.won+wins)/(state.baseline.won+state.baseline.lost+wins+losses)*100)+'%'},proof:{label:'Proofs accepted',value:state.pacts.reduce((n,p)=>n+Object.values(p.proofs).filter(v=>v.status==='accepted').length,0)},completed:{label:'Promises kept',value:state.pacts.filter(p=>p.status==='completed').length},races:{label:'Runs logged',value:state.pacts.filter(p=>p.type==='Race').reduce((n,p)=>n+(p.scores.EA||0),0)}};}
function renderProfile(){
  const s=stats();$('#memberName').textContent=state.profile.name;$('#memberStreak').textContent=s.streak.value.replace('d',' DAY STREAK');$('.header-avatar').innerHTML=safeImage(state.profile.photo)?`<img src="${e(safeImage(state.profile.photo))}" alt="Your profile">`:e(initials(state.profile.name));if($('#settingsPhotoPreview')){$('#settingsPhotoPreview').src=safeImage(state.profile.photo);$('#settingsPhotoPreview').hidden=!safeImage(state.profile.photo);}$('#profileGreeting').innerHTML=`Good on you,<br><em>${e(state.profile.name.split(' ')[0])}.</em>`;$('#profileBio').textContent=state.profile.bio;
  $('#backStats').innerHTML=state.stats.map(id=>`<span><small>${s[id].label}</small><strong>${e(s[id].value)}</strong></span>`).join('');
  $('#profileNumbers').innerHTML=['won','streak','accuracy'].map(id=>`<div><strong>${e(s[id].value)}</strong><span>${s[id].label}</span></div>`).join('');
  const achievements=[['12','The regular','A 12-day streak.',parseInt(s.streak.value)>=12],['P','Proof of character','Three accepted proofs.',s.proof.value>=3],['42','Called it','Win 42 pacts.',s.won.value>=42],['7','A week well spent','Keep seven promises.',s.completed.value>=7]];
  $('#achievementRow').innerHTML=achievements.map(([glyph,title,desc,earned])=>`<article class="achievement ${earned?'':'locked'}"><span class="achievement-medal" aria-hidden="true">${glyph}</span><small>${earned?'EARNED':'STILL TO COME'}</small><h3>${title}</h3><p>${desc}</p></article>`).join('');
  if(!$('#statEditor').hidden)renderStatEditor();
}
function renderSettings(){ $('#settingsName').value=state.profile.name;$('#settingsBio').value=state.profile.bio;$('#settingsEmail').value=state.profile.email;$('#motionSetting').checked=state.settings.motion;$('#reminderSetting').checked=state.settings.reminders; }
function applySettings(){document.body.classList.toggle('motion-off',!state.settings.motion);window.dispatchEvent(new CustomEvent('pact:motion',{detail:state.settings.motion}));}
function renderAll(){renderHome();renderSpaces();renderActivity();renderProfile();if(currentRoute.startsWith('challenge/'))renderChallenge(decodeId(currentRoute.slice(10)));applySettings();window.dispatchEvent(new Event('pact:render'));}
function actionLabel(p){if(p.status==='pending')return 'I’m in ↗';if(p.status==='completed')return 'Your card ↗';return {Habit:M.completedDays(p).size===p.totalDays?'Seal this achievement ↗':'Check in ↗',Prediction:p.votes.EA?'Your prediction is sealed':'Pick your side below',Race:'Log a run ↗',Number:Number.isFinite(p.guesses.EA)?'Your guess is sealed':'Leave your guess below',Jar:'Record a slip-up ↗',Elimination:'Your people, still in play'}[p.type];}
function renderChallenge(id){
  const p=find(id);if(!p){$('#challengeScreen').innerHTML=empty('This pact is no longer here.','Return to your collection to find another.');return;}
  const progress=M.progress(p),pending=Object.entries(p.proofs).filter(([,proof])=>proof.status==='pending');
  const canPrimary=p.status!=='active'||!['Prediction','Number','Elimination'].includes(p.type);
  $('#challengeScreen').innerHTML=`<a class="back-link" href="#spaces">← Your pacts</a><header class="detail-heading"><div><p class="eyebrow">${e(p.room)} / ${e(p.type)}</p><h1>${e(p.title)}</h1></div><span class="status-pill ${p.status}">${p.status==='active'?'On the table':p.status==='pending'?'An open invitation':'A promise kept'}</span></header><div class="detail-main"><div class="detail-object"><div class="scene-slot" data-scene="${asset(p)}" data-scene-role="detail" data-pact-id="${e(p.id)}"><img class="scene-poster" src="assets/objects/${asset(p)}.png" alt="${e(p.type)} pact object"></div><div class="detail-object-foot"><span>${objectLabels[asset(p)]}</span><span>Yours to make real.</span></div></div><div class="detail-panel"><div class="detail-kicker"><p class="eyebrow">${p.status==='completed'?'The story so far':'A little friendly pressure'}</p>${avatars(p.people)}</div><h2>${p.status==='completed'?'You showed up.':p.type==='Habit'?'One day at a time.':p.type==='Prediction'?'Put your word on it.':p.type==='Race'?'A little further, together.':p.type==='Number'?'A feeling. A number.':p.type==='Jar'?'Keep it honest.':'Still in good company.'}</h2><p class="detail-summary">${e(summary(p))}</p>${p.type==='Habit'?`<div class="meter" role="progressbar" aria-label="Days kept" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${progress}"><span style="width:${progress}%"></span></div>`:''}<dl class="detail-facts"><div><dt>What's at stake</dt><dd>${e(p.stake)}</dd></div><div><dt>The finish line</dt><dd>${formatDate(endDate(p))}</dd></div><div><dt>Your people</dt><dd>${p.people.map(personName).map(e).join(', ')}</dd></div><div><dt>The rule</dt><dd>${e(p.proof)}</dd></div></dl>${p.status==='completed'?resultPanel(p):''}${p.status==='pending'?`<p class="detail-summary">Someone thinks this could be interesting. Join the pact to take part.</p>`:typeBoard(p)}${canPrimary?`<div class="detail-buttons"><button class="button primary" data-primary="${e(p.id)}">${actionLabel(p)}</button><a class="button" href="#activity">Room activity</a></div>`:''}${pending.length?`<div class="detail-board"><h3>Proof waiting for review</h3>${pending.map(([day])=>`<button class="button" data-proof-open="${e(p.id)}" data-day="${day}">Review day ${day} ↗</button>`).join('')}</div>`:''}${p.status==='active'&&['Prediction','Number','Race','Jar'].includes(p.type)?`<div class="detail-board"><button class="text-button" data-resolve="${e(p.id)}">Close this pact and record the result ↗</button></div>`:''}</div></div><section class="detail-rules"><article><h3>The promise</h3><p>${e(p.title)}. ${p.totalDays} ${p.totalDays===1?'day':'days'}, starting ${formatDate(p.startDate)}.</p></article><article><h3>The reward</h3><p>${e(p.reward)}</p></article><article><h3>Between friends</h3><p>Keep it kind. Keep it honest. Stakes are recorded here; settling up is between your people.</p></article></section>`;
  window.dispatchEvent(new Event('pact:render'));
}
function resultPanel(p){let detail=p.type==='Prediction'?`The answer was ${p.result||'recorded'}.`:p.type==='Number'?`The actual result: ${p.result}.`:'Another commitment, kept.';const winners=p.winners||[p.winner||'EA'];return `<div class="result-banner"><h3>${winners.includes('EA')?'A little proud? You should be.':'A good game, well played.'}</h3><p>${e(detail)} ${winners.length?`${winners.map(personName).map(e).join(' & ')} ${winners.length>1?'take':'takes'} this one.`:'No winning guesses this time.'}</p></div>`;}
function typeBoard(p){
  const disabled=p.status==='completed'?'disabled':'';
  if(p.type==='Habit'){const completed=M.completedDays(p);return `<section class="detail-board"><h3>Your ${p.totalDays}-day promise</h3><div class="calendar-grid">${Array.from({length:p.totalDays},(_,i)=>{const day=i+1,date=M.dateOffset(i,new Date(p.startDate+'T12:00:00')),pending=p.proofs[day]?.status==='pending',done=completed.has(day);return `<button class="calendar-day ${done?'done':pending?'pending':''} ${day===M.nextDay(p)?'today':''}" data-day-open="${e(p.id)}" data-day="${day}" aria-label="Day ${day}, ${formatDate(date)}, ${done?'accepted':pending?'proof pending':'not checked in'}"><small>${new Date(date+'T12:00:00').toLocaleDateString('en',{weekday:'short'})}</small><strong>${date.slice(-2)}</strong><span>${done?'✓':pending?'◷':'·'}</span></button>`;}).join('')}</div><div class="calendar-legend"><span>✓ Kept</span><span>◷ In review</span><span>· Still to come</span></div></section>`;}
  if(p.type==='Prediction')return `<section class="detail-board"><h3>${p.status==='completed'?'The sealed predictions, revealed.':'Two sides. One promise.'}</h3><div class="sealed-board">${['yes','no'].map(side=>`<button class="sealed-choice ${p.votes.EA===side?'picked':''}" data-vote="${e(p.id)}" data-side="${side}" ${disabled}><span class="seal-mini" aria-hidden="true">P</span>${side==='yes'?'Yes':'No'}<small>${p.status==='completed'?`${Object.values(p.votes).filter(v=>v===side).length} predictions`:p.votes.EA===side?'Your sealed choice':'Results stay hidden'}</small></button>`).join('')}</div></section>`;
  if(p.type==='Race'){const ranked=p.people.slice().sort((a,b)=>(p.scores[b]||0)-(p.scores[a]||0));return `<section class="detail-board"><h3>A little friendly competition.</h3>${ranked.map((id,i)=>`<div class="leaderboard-row"><span>0${i+1}</span><span class="header-avatar">${e(id)}</span><strong>${e(personName(id))}${id==='EA'?' · you':''}</strong><em>${p.scores[id]||0} runs</em></div>`).join('')}</section>`;}
  if(p.type==='Number')return `<section class="detail-board"><h3>${p.status==='completed'?'Every guess, on the table.':'What’s your best guess?'}</h3>${p.status==='completed'?p.people.map(id=>`<div class="leaderboard-row"><span>◇</span><span class="header-avatar">${e(id)}</span><strong>${e(personName(id))}</strong><em>${Number.isFinite(p.guesses[id])?p.guesses[id]:'No guess'}</em></div>`).join(''):`<form class="guess-form" data-guess-form="${e(p.id)}"><input type="number" step="any" name="guess" required aria-label="Your number guess" placeholder="Your number" value="${Number.isFinite(p.guesses.EA)?p.guesses.EA:''}"><button class="button primary">Seal my guess ↗</button></form><p class="form-hint">${Number.isFinite(p.guesses.EA)?`Your guess: ${p.guesses.EA}. `:''}Other guesses stay face down until the reveal.</p>`}</section>`;
  if(p.type==='Jar'){const amount=parseFloat(String(p.stake).replace(/[^0-9.]/g,''));return `<section class="detail-board"><p class="eyebrow">Little slips. Duly recorded.</p><div class="jar-count">${p.violations}<small>${Number.isFinite(amount)?`${e(p.stake)} each · ${(amount*p.violations).toLocaleString('en-IN')} recorded`:'A shared record between friends.'}</small></div></section>`;}
  return `<section class="detail-board"><h3>Last one standing.</h3><div class="elimination-list">${p.people.map(id=>`<div class="pass-row ${p.retired.includes(id)?'retired':''}"><strong>${e(personName(id))}</strong><small>${p.retired.includes(id)?'RETIRED':'STILL IN PLAY'}</small>${p.status==='active'&&!p.retired.includes(id)&&p.people.length-p.retired.length>1?`<button data-retire="${e(p.id)}" data-person="${e(id)}">Record withdrawal ↗</button>`:''}</div>`).join('')}</div>${p.status==='active'&&p.people.length-p.retired.length===1?`<button class="button primary" data-resolve="${e(p.id)}">Celebrate the survivor ↗</button>`:''}</section>`;
}
function dialog(html){photoDraft=null;$('#dialogBody').innerHTML=html;if(!$('#pactDialog').open)$('#pactDialog').showModal();}
function closeDialog(){if($('#pactDialog').open)$('#pactDialog').close();photoDraft=null;}
function primary(id){const p=find(id);if(!p)return;if(p.status==='pending'){transaction(()=>{p.status='active';activity('invite','You put your word on it.',p.title,id);},'You’re in. Make it a good one.','seal');return;}if(p.status==='completed'){location.hash='profile';return;}if(p.type==='Habit'){if(M.completedDays(p).size===p.totalDays)resolveDialog(id);else dayDialog(id,M.nextDay(p));return;}if(p.type==='Race'){transaction(()=>{p.scores.EA=(p.scores.EA||0)+1;activity('race','One more run. One step closer.',`${p.title} · ${p.scores.EA} runs`,id);},'Run logged. Nicely done.','race');return;}if(p.type==='Jar')dialog(`<h2 id="dialogTitle">Caught a little slip?</h2><p>Record one violation for ${e(p.title)}. This adds ${e(p.stake)} to the shared record.</p><div class="dialog-actions"><button class="button primary" data-add-violation="${e(id)}">Record one slip ↗</button><button class="button" data-close>Not this time</button></div>`);}
function dayDialog(id,day){
  const p=find(id);if(!p)return;const proof=p.proofs[day],done=M.completedDays(p).has(Number(day));
  if(proof&&!proof.sample){proofDialog(id,day);return;}
  if(p.startDate&&M.dateOffset(day-1,new Date(p.startDate+'T12:00:00'))>M.dateOffset(0)){dialog(`<h2 id="dialogTitle">One day at a time.</h2><p>Day ${day} opens on ${formatDate(M.dateOffset(day-1,new Date(p.startDate+'T12:00:00')))}. Come back then to keep this promise.</p><button class="button primary" data-close>See you then ↗</button>`);return;}
  if(done||p.status==='completed'){dialog(`<h2 id="dialogTitle">Day ${day}. You showed up.</h2><p>${e(p.title)} · ${formatDate(M.dateOffset(day-1,new Date(p.startDate+'T12:00:00')))}</p><div class="result-banner"><h3>A promise kept.</h3><p>${p.proofMode==='photo'?'Proof accepted by the room.':'Your honest check-in is recorded.'}</p></div><button class="button primary" data-close>Keep it going ↗</button>`);return;}
  dialog(`<h2 id="dialogTitle">Day ${day}. Make it real.</h2><p>${e(p.proof)}</p>${p.proofMode==='photo'?`<label for="proofUpload">Your photo proof</label><input id="proofUpload" type="file" accept="image/png,image/jpeg,image/webp"><img id="uploadPreview" class="upload-preview" hidden alt="Your selected proof"><p class="form-hint">Your proof will wait for review before this day is counted.</p><p id="uploadError" class="error-text" role="alert"></p>`:'<p>An honest check-in. A small promise kept.</p>'}<div class="dialog-actions"><button class="button primary" data-check-in="${e(id)}" data-day="${day}" ${p.proofMode==='photo'?'disabled':''}>${p.proofMode==='photo'?'Submit proof':'Mark day kept'} ↗</button><button class="button" data-close>Come back later</button></div>`);
}
function proofDialog(id,day){const p=find(id),proof=p?.proofs[day];if(!proof)return;dialog(`<h2 id="dialogTitle">A little proof of showing up.</h2><p>${e(p.title)} · Day ${day}</p><figure class="proof-display">${safeImage(proof.dataUrl)?`<img src="${e(safeImage(proof.dataUrl))}" alt="Photo proof for day ${day}">`:'<div class="sample-proof"><strong>11:42</strong><span>LIGHTS OUT</span></div>'}<figcaption>${proof.status==='accepted'?'A promise kept.':'Waiting for the room.'}</figcaption>${proof.status==='accepted'?'<span class="proof-seal">P</span>':''}</figure>${proof.status==='pending'?`<p class="dialog-note">Review the photo against the pact's proof rule. This device holds the shared prototype record.</p><div class="dialog-actions"><button class="button primary" data-accept-proof="${e(id)}" data-day="${day}">Accept proof ✓</button><button class="button" data-reject-proof="${e(id)}" data-day="${day}">Ask for another</button></div>`:'<button class="button" data-close>Back to the pact</button>'}`);}
function reviewActivity(id){const a=state.activity.find(a=>a.id===id);if(!a)return;if(a.day){proofDialog(a.pactId,a.day);return;}dialog(`<h2 id="dialogTitle">Naina kept her word.</h2><p>Sleep before midnight · sample check-in</p><figure class="proof-display"><div class="sample-proof"><strong>11:42</strong><span>LIGHTS OUT</span></div><figcaption>Naina’s proof</figcaption></figure><p class="dialog-note">The photo is a sample in this local prototype. You can review its state without affecting your own check-in.</p><div class="dialog-actions"><button class="button primary" data-review-sample="${e(id)}" data-result="accepted">Accept proof ✓</button><button class="button" data-review-sample="${e(id)}" data-result="requested">Ask for another</button></div>`);}
function resolveDialog(id){const p=find(id);if(!p)return;dialog(`<h2 id="dialogTitle">Time to call it.</h2><p>This closes ${e(p.title)} and records the result for everyone in the pact.</p>${p.type==='Prediction'?'<label for="actualResult">What actually happened?</label><select id="actualResult"><option value="yes">Yes — it happened</option><option value="no">No — it didn’t</option></select>':p.type==='Number'?'<label for="actualResult">The actual number</label><input id="actualResult" type="number" step="any" placeholder="Enter the result">':''}<div class="dialog-actions"><button class="button primary" data-confirm-result="${e(id)}">Record result & reveal ↗</button><button class="button" data-close>Keep it open</button></div><p id="resultError" class="error-text" role="alert"></p>`);}
function updateCreate(infer=false){const text=$('#ideaInput').value.trim();if(infer&&!selectedType)$('#pactType').value=M.inferType(text);const type=$('#pactType').value;$('#typeHint').textContent=hints[type];$('#proofField').hidden=type!=='Habit';$('#createObjectLabel').textContent=objectLabels[asset(type)];$('#createPreviewTitle').textContent=text||'A promise taking shape.';const slot=$('.create-preview .scene-slot');slot.dataset.scene=asset(type);slot.querySelector('img').src=`assets/objects/${asset(type)}.png`;window.dispatchEvent(new Event('pact:render'));}
function buildDraft(){
  const title=$('#ideaInput').value.trim(),type=$('#pactType').value,context=$('#pactContext').value;
  if(!title)return null;const friendNames=context==='Personal'?[]:$('#pactPeople').value.split(',').map(s=>s.trim()).filter(Boolean).slice(0,context==='Couple'?1:11);
  if(context!=='Personal'&&!friendNames.length){$('#pactPeople').setCustomValidity('Add at least one person to this pact.');$('#pactPeople').reportValidity();return null;}
  const people=['EA'],peopleNames={};for(const name of friendNames){let id=initials(name);if(people.includes(id))id+=String(people.length);people.push(id);peopleNames[id]=name;}
  return {id:M.uid(),type,title,context,people,peopleNames,room:context==='Personal'?'A Little Better':context==='Couple'?'Table for Two':'Your Good Company',status:'active',startDate:$('#pactStart').value,totalDays:Number($('#pactDuration').value),stake:$('#pactStake').value.trim()||'Just for fun',proofMode:type==='Habit'?$('#pactProof').value:'log',proof:type==='Habit'&&$('#pactProof').value==='photo'?'A photo for the room to review.':hints[type],reward:'A promise worth keeping. A little pride earned.',logs:[],proofs:{},votes:{},scores:{},guesses:{},retired:[],violations:0,createdAt:new Date().toISOString()};
}
function renderStatEditor(){const s=stats();$('#statEditor').innerHTML=`<p class="form-hint">Choose up to four stats. Drag a row, or use the arrows to reorder.</p>${state.stats.map((id,i)=>`<div class="stat-edit-row" draggable="true" data-stat-row="${i}"><span>${s[id].label} · ${e(s[id].value)}</span><div class="stat-edit-actions"><button data-stat-move="${i}" data-direction="-1" aria-label="Move ${s[id].label} up" ${i===0?'disabled':''}>↑</button><button data-stat-move="${i}" data-direction="1" aria-label="Move ${s[id].label} down" ${i===state.stats.length-1?'disabled':''}>↓</button><button data-stat-remove="${i}" aria-label="Remove ${s[id].label}">×</button></div></div>`).join('')}${state.stats.length<4?`<div class="stat-add"><select id="addStat" aria-label="Choose a statistic">${Object.entries(s).filter(([id])=>!state.stats.includes(id)).map(([id,v])=>`<option value="${id}">${v.label}</option>`).join('')}</select><button class="button" data-stat-add>Add stat</button></div>`:''}`;}
function downloadBlob(blob,filename){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);}
async function downloadCard(){await document.fonts.ready;const canvas=document.createElement('canvas');canvas.width=1200;canvas.height=760;const c=canvas.getContext('2d');const g=c.createLinearGradient(0,0,1200,760);g.addColorStop(0,'#592633');g.addColorStop(1,'#23141b');c.fillStyle=g;c.beginPath();c.roundRect(0,0,1200,760,32);c.fill();c.strokeStyle='#ad8961';c.lineWidth=2;c.strokeRect(25,25,1150,710);c.fillStyle='#f1e7d8';c.font='76px Fraunces, Georgia';c.fillText('Pact',75,120);c.fillStyle='#c4a478';c.font='16px "DM Sans"';c.fillText('THE PRIVATE GAME ROOM',780,95);let fontSize=44;c.font=`${fontSize}px Fraunces, Georgia`;while(c.measureText(state.profile.name).width>1000&&fontSize>20){c.font=`${--fontSize}px Fraunces, Georgia`;}c.fillStyle='#f1e7d8';c.fillText(state.profile.name,75,205);const s=stats();state.stats.forEach((id,i)=>{const x=75+(i%2)*570,y=300+Math.floor(i/2)*175;c.fillStyle='#b5a59e';c.font='23px "DM Sans"';c.fillText(s[id].label,x,y);c.fillStyle='#f1e7d8';c.font='76px Fraunces, Georgia';c.fillText(String(s[id].value),x,y+88);});c.fillStyle='#c4a478';c.font='15px "DM Sans"';c.fillText('SMALL PROMISES. BETTER COMPANY.',75,695);canvas.toBlob(blob=>{if(blob)downloadBlob(blob,'my-pact-card.png');},'image/png');}
function currentScrollTop(){return window.scrollY;}
function scrollRootTo(top,behavior='auto'){window.scrollTo({top,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches||!state.settings.motion?'auto':behavior});}
function rememberPosition(){scrollPositions[currentRoute||'home']=currentScrollTop();try{sessionStorage.setItem('pactRoomScroll',JSON.stringify(scrollPositions));}catch{}}
function showView(route,initial=false){
  const [view,id]=route.split('/'),valid=['home','spaces','challenge','create','activity','profile','settings'];if(!valid.includes(view)){location.replace('#home');return;}
  if(!initial)rememberPosition();closeDialog();currentRoute=route;
  $$('.view').forEach(el=>{const active=el.id===view;el.hidden=!active;el.classList.toggle('active',active);});
  $$('[data-nav]').forEach(a=>{const active=a.dataset.nav===view||(view==='challenge'&&a.dataset.nav==='spaces')||(view==='settings'&&a.dataset.nav==='profile');a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
  if(view==='challenge')renderChallenge(decodeId(id||''));if(view==='settings')renderSettings();
  document.title=`${view==='home'?'Your word. Made real.':view==='challenge'?(find(decodeId(id||''))?.title||'Your pact'):{spaces:'Your pacts',create:'Make a pact',activity:'Room activity',profile:'Your card',settings:'The little details'}[view]} — Pact`;
  const active=$('#'+view);active.classList.remove('view-enter');requestAnimationFrame(()=>{scrollRootTo(scrollPositions[route]||0);active.classList.add('view-enter');window.dispatchEvent(new Event('pact:render'));if(!initial){const heading=active.querySelector('h1');if(heading){heading.setAttribute('tabindex','-1');heading.focus({preventScroll:true});}}});
}
// All generated controls share one delegated event boundary.
async function onClick(event){
  const target=event.target.closest('button,[data-explore]');if(!target)return;
  if(target.hasAttribute('data-close')){closeDialog();return;}
  if(target.hasAttribute('data-explore')){$('#ritual').scrollIntoView({behavior:state.settings.motion?'smooth':'auto'});return;}
  if(target.dataset.filter){filter=target.dataset.filter;$$('[data-filter]').forEach(b=>{const on=b.dataset.filter===filter;b.classList.toggle('active',on);b.setAttribute('aria-pressed',on);});renderHome();return;}
  if(target.dataset.status){statusFilter=target.dataset.status;renderSpaces();return;}
  if(target.dataset.primary){primary(target.dataset.primary);return;}
  if(target.dataset.dayOpen){dayDialog(target.dataset.dayOpen,Number(target.dataset.day));return;}
  if(target.dataset.proofOpen){proofDialog(target.dataset.proofOpen,Number(target.dataset.day));return;}
  if(target.dataset.review){reviewActivity(target.dataset.review);return;}
  if(target.dataset.resolve){resolveDialog(target.dataset.resolve);return;}
  if(target.dataset.checkIn){const id=target.dataset.checkIn,day=Number(target.dataset.day);if(transaction(()=>{const p=find(id);if(!M.recordDay(p,day,photoDraft))return false;activity(p.proofMode==='photo'?'proof':'check',p.proofMode==='photo'?'A little proof, ready for review.':'You kept a small promise.',`${p.title} · Day ${day}`,id,p.proofMode==='photo'?{pending:true,day}:{});},photoDraft?'Proof submitted. Your room can review it.':'Day kept. Nicely done.','check'))closeDialog();return;}
  if(target.dataset.acceptProof||target.dataset.rejectProof){const accept=!!target.dataset.acceptProof,id=target.dataset.acceptProof||target.dataset.rejectProof,day=Number(target.dataset.day);if(transaction(()=>{const p=find(id);if(accept){if(!M.acceptProof(p,day))return false;}else delete p.proofs[day];state.activity.filter(a=>a.pactId===id&&a.day===day&&a.pending).forEach(a=>a.pending=false);activity('proof',accept?'The room stamped your proof.':'One more photo, please.',`${p.title} · Day ${day}`,id);},accept?'Proof accepted. The day is yours.':'Another photo requested.',accept?'seal':null))closeDialog();return;}
  if(target.dataset.reviewSample){const id=target.dataset.reviewSample,result=target.dataset.result;if(transaction(()=>{const a=state.activity.find(a=>a.id===id);a.pending=false;const p=find(a.pactId);if(p){p.memberProofs={...(p.memberProofs||{}),NA:{day:4,status:result}};}activity('proof',result==='accepted'?'Naina’s proof earned its stamp.':'Naina was asked for another photo.','Sleep before midnight',a.pactId);},result==='accepted'?'Proof accepted. Naina keeps the streak.':'A request is waiting in Activity.','seal'))closeDialog();return;}
  if(target.dataset.vote){const id=target.dataset.vote,p=find(id);if(p.status!=='active')return;transaction(()=>{p.votes.EA=target.dataset.side;activity('check','Your prediction is sealed.',p.title,id);},'Sealed. The other predictions stay hidden.','seal');return;}
  if(target.dataset.addViolation){const id=target.dataset.addViolation;if(transaction(()=>{const p=find(id);if(p.status!=='active')return false;p.violations+=1;activity('jar','One little slip, on the record.',`${p.title} · ${p.violations} recorded`,id);},'Recorded. The jar remembers.','coin'))closeDialog();return;}
  if(target.dataset.retire){const id=target.dataset.retire,person=target.dataset.person;dialog(`<h2 id="dialogTitle">One less in the running.</h2><p>Record ${e(personName(person))} as withdrawn from ${e(find(id).title)}?</p><div class="dialog-actions"><button class="button primary" data-confirm-retire="${e(id)}" data-person="${e(person)}">Record withdrawal</button><button class="button" data-close>Keep them in</button></div>`);return;}
  if(target.dataset.confirmRetire){const id=target.dataset.confirmRetire,person=target.dataset.person;if(transaction(()=>{const p=find(id);if(p.status!=='active'||p.retired.includes(person)||p.people.length-p.retired.length<=1)return false;p.retired.push(person);activity('check',`${personName(person)} stepped out of the running.`,p.title,id);},'Withdrawal recorded.','retire'))closeDialog();return;}
  if(target.dataset.confirmResult){const id=target.dataset.confirmResult,actual=$('#actualResult')?.value;if(transaction(()=>{const p=find(id);if(!M.resolve(p,actual)){return false;}activity('result','A pact becomes a keepsake.',p.title,id);},'The result is on the table.','reveal'))closeDialog();else $('#resultError').textContent='Add the result and make sure this pact is ready to close.';return;}
  if(target.id==='sealPact'){if(!draft)return;const id=draft.id;if(transaction(()=>{state.peopleNames={...state.peopleNames,...draft.peopleNames};const record={...draft};delete record.peopleNames;state.pacts.unshift(record);activity('create','You put a new promise on the table.',record.title,id);},'A new promise. Make it a good one.','seal')){draft=null;closeDialog();$('#createForm').reset();$('#peopleField').hidden=true;$('#pactStart').value=M.dateOffset(0);selectedType=false;updateCreate();location.hash='challenge/'+id;}return;}
  if(target.dataset.suggestion){$('#ideaInput').value=target.dataset.suggestion;selectedType=false;updateCreate(true);return;}
  if(target.dataset.statMove!==undefined){const i=Number(target.dataset.statMove),j=i+Number(target.dataset.direction);transaction(()=>{if(j<0||j>=state.stats.length)return false;[state.stats[i],state.stats[j]]=[state.stats[j],state.stats[i]];});return;}
  if(target.dataset.statRemove!==undefined){transaction(()=>{state.stats.splice(Number(target.dataset.statRemove),1);});return;}
  if(target.hasAttribute('data-stat-add')){const id=$('#addStat').value;transaction(()=>{if(state.stats.length<4&&!state.stats.includes(id))state.stats.push(id);});return;}
}
function init(){
  $('#pactType').innerHTML=M.TYPES.map(type=>`<option>${type}</option>`).join('');$('#pactStart').value=M.dateOffset(0);renderAll();
  document.addEventListener('click',onClick);$('.skip-link').addEventListener('click',event=>{event.preventDefault();$('#main').setAttribute('tabindex','-1');$('#main').focus({preventScroll:true});scrollRootTo(0);});$('#closeDialog').addEventListener('click',closeDialog);$('#pactDialog').addEventListener('click',event=>{if(event.target===$('#pactDialog')){const r=event.target.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)closeDialog();}});
  $('#pactSearch').addEventListener('input',event=>{search=event.target.value;renderSpaces();});$('#ideaInput').addEventListener('input',()=>updateCreate(true));$('#pactType').addEventListener('change',()=>{selectedType=true;updateCreate();});$('#pactContext').addEventListener('change',()=>{$('#peopleField').hidden=$('#pactContext').value==='Personal';});$('#pactPeople').addEventListener('input',()=>$('#pactPeople').setCustomValidity(''));
  $('#createForm').addEventListener('submit',event=>{event.preventDefault();draft=buildDraft();if(!draft)return;dialog(`<h2 id="dialogTitle">A promise worth keeping.</h2><p>${e(draft.title)}</p><dl class="review-list">${[['The object',draft.type],['Your people',draft.people.map(id=>draft.peopleNames[id]||personName(id)).join(', ')],['The stake',draft.stake],['Starts',formatDate(draft.startDate)],['Duration',draft.totalDays+' days'],['Your proof',draft.proof]].map(([k,v])=>`<div><dt>${k}</dt><dd>${e(v)}</dd></div>`).join('')}</dl><p class="dialog-note">This creates a pact on this device. Adding names records your people; it doesn't send invitations.</p><div class="dialog-actions"><button class="button primary" id="sealPact">Seal the pact ↗</button><button class="button" data-close>Fine-tune it</button></div>`);});
  document.addEventListener('submit',event=>{const form=event.target.closest('[data-guess-form]');if(!form)return;event.preventDefault();const value=Number(new FormData(form).get('guess')),id=form.dataset.guessForm;if(!Number.isFinite(value))return;transaction(()=>{const p=find(id);if(p.status!=='active')return false;p.guesses.EA=value;activity('number','Your best guess, safely sealed.',p.title,id);},'Your guess is sealed.','seal');});
  document.addEventListener('change',async event=>{if(!['proofUpload','profileUpload'].includes(event.target.id))return;const profileUpload=event.target.id==='profileUpload';const file=event.target.files[0],input=event.target;photoDraft=null;const button=$('[data-check-in]');if(button)button.disabled=true;if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>12*1024*1024){if(profileUpload)toast('Choose a PNG, JPG or WebP smaller than 12 MB.');else $('#uploadError').textContent='Choose a PNG, JPG or WebP smaller than 12 MB.';return;}try{const bitmap=await createImageBitmap(file),canvas=document.createElement('canvas'),scale=Math.min(1,1000/Math.max(bitmap.width,bitmap.height));canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();if(!input.isConnected)return;if(profileUpload){transaction(()=>{state.profile.photo=canvas.toDataURL('image/jpeg',.82);},'Your profile photo is saved.');return;}photoDraft={dataUrl:canvas.toDataURL('image/jpeg',.78),name:file.name,createdAt:new Date().toISOString()};$('#uploadPreview').src=photoDraft.dataUrl;$('#uploadPreview').hidden=false;$('#uploadError').textContent='';button.disabled=false;}catch{if(profileUpload)toast('That photo could not be opened.');if($('#uploadError'))$('#uploadError').textContent='That photo couldn’t be opened. Please choose another.';}});
  $('#profileCard').addEventListener('click',()=>{const on=$('#profileCard').classList.toggle('flipped');$('#profileCard').setAttribute('aria-pressed',on);});$('#customizeCard').addEventListener('click',()=>{const editor=$('#statEditor');editor.hidden=!editor.hidden;$('#customizeCard').textContent=editor.hidden?'Customize card':'Done customizing';if(!editor.hidden){$('#profileCard').classList.add('flipped');$('#profileCard').setAttribute('aria-pressed','true');renderStatEditor();}});$('#downloadCard').addEventListener('click',downloadCard);
  $('#statEditor').addEventListener('dragstart',event=>{const row=event.target.closest('[data-stat-row]');if(row){dragStat=Number(row.dataset.statRow);row.classList.add('dragging');event.dataTransfer.effectAllowed='move';}});$('#statEditor').addEventListener('dragover',event=>event.preventDefault());$('#statEditor').addEventListener('drop',event=>{event.preventDefault();const row=event.target.closest('[data-stat-row]');if(row&&dragStat!==null){const to=Number(row.dataset.statRow),from=dragStat;transaction(()=>{const [id]=state.stats.splice(from,1);state.stats.splice(to,0,id);});}dragStat=null;});$('#statEditor').addEventListener('dragend',()=>{$$('.dragging').forEach(el=>el.classList.remove('dragging'));dragStat=null;});
  $('#settingsForm').addEventListener('submit',event=>{event.preventDefault();const name=$('#settingsName').value.trim();if(!name){$('#settingsName').setCustomValidity('Give your card a name.');$('#settingsName').reportValidity();return;}transaction(()=>{state.profile.name=name;state.profile.bio=$('#settingsBio').value.trim();state.profile.email=$('#settingsEmail').value.trim();},'Your details are saved.');});$('#settingsName').addEventListener('input',()=>$('#settingsName').setCustomValidity(''));
  $('#motionSetting').addEventListener('change',event=>{const motion=event.target.checked;transaction(()=>{state.settings.motion=motion;});});$('#reminderSetting').addEventListener('change',event=>{const reminders=event.target.checked;transaction(()=>{state.settings.reminders=reminders;});});$('#exportData').addEventListener('click',()=>downloadBlob(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),'my-pact-records.json'));
  window.addEventListener('hashchange',()=>showView(location.hash.slice(1)||'home'));window.addEventListener('beforeunload',rememberPosition);let scrollTimer;window.addEventListener('scroll',()=>{clearTimeout(scrollTimer);scrollTimer=setTimeout(rememberPosition,150);},{passive:true});showView(location.hash.slice(1)||'home',true);
}
window.PactApp={getState:()=>state,getPact:find,toast,currentScrollTop,scrollRootTo};
init();
})();
